# Generated by Django 3.1.5 on 2021-02-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_api.productcollections', verbose_name='Подборки'),
        ),
    ]
