# Generated by Django 3.1.5 on 2021-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='product',
        ),
        migrations.AddField(
            model_name='favourites',
            name='product',
            field=models.ManyToManyField(related_name='favourites', to='shop_api.Product'),
        ),
    ]
