# Generated by Django 3.1.4 on 2021-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_productcollections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order', through='shop_api.Position', to='shop_api.Product'),
        ),
    ]
