# Generated by Django 3.1.4 on 2021-02-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0005_auto_20210227_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(to='shop_api.UserMethods'),
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
