# Generated by Django 3.1.4 on 2021-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_auto_20210227_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(related_name='products', to='shop_api.UserMethods'),
        ),
    ]
