# Generated by Django 3.1.5 on 2021-02-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_auto_20210215_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorites',
        ),
        migrations.AddField(
            model_name='favourites',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='shop_api.product', verbose_name='Товар'),
        ),
    ]
