# Generated by Django 3.1.5 on 2021-02-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0009_auto_20210216_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='shop_api.usermethods', verbose_name='Пользователь'),
        ),
    ]
