# Generated by Django 3.1.5 on 2021-02-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0010_auto_20210216_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='shop_api.product', verbose_name='Товар'),
        ),
    ]
